platform :ios, "8.0"

pod "AFNetworking"
pod "SDWebImage"
pod "MJExtension"
pod "MJRefresh"
pod "Masonry"
pod "SDCycleScrollView"
pod "TXScrollLabelView"
pod "SVProgressHUD"
pod "PYSearch"


target :"CDDStoreDemo"
